export const all_languages = [
    { label: "Afrikaans", value: "afrikaans" },
    { label: "Shqip", value: "albanian" },
    { label: "አማርኛ", value: "amharic" },
    { label: "العربية", value: "arabic" },
    { label: "Հայերեն", value: "armenian" },
    { label: "Azərbaycan dili", value: "azerbaijani" },
    { label: "Euskara", value: "basque" },
    { label: "Беларуская", value: "belarusian" },
    { label: "বাংলা", value: "bengali" },
    { label: "Bosanski", value: "bosnian" },
    { label: "Български", value: "bulgarian" },
    { label: "Català", value: "catalan" },
    { label: "中文", value: "chinese" },
    { label: "Hrvatski", value: "croatian" },
    { label: "Čeština", value: "czech" },
    { label: "Dansk", value: "danish" },
    { label: "Nederlands", value: "dutch" },
    { label: "English", value: "english" },
    { label: "Eesti", value: "estonian" },
    { label: "Suomi", value: "finnish" },
    { label: "Français", value: "french" },
    { label: "ქართული", value: "georgian" },
    { label: "Deutsch", value: "german" },
    { label: "Ελληνικά", value: "greek" },
    { label: "ગુજરાતી", value: "gujarati" },
    { label: "Kreyòl Ayisyen", value: "haitian_creole" },
    { label: "עברית", value: "hebrew" },
    { label: "हिन्दी", value: "hindi" },
    { label: "Magyar", value: "hungarian" },
    { label: "Íslenska", value: "icelandic" },
    { label: "Bahasa Indonesia", value: "indonesian" },
    { label: "Gaeilge", value: "irish" },
    { label: "Italiano", value: "italian" },
    { label: "日本語", value: "japanese" },
    { label: "ಕನ್ನಡ", value: "kannada" },
    { label: "Қазақ тілі", value: "kazakh" },
    { label: "한국어", value: "korean" },
    { label: "Latviešu", value: "latvian" },
    { label: "Lietuvių", value: "lithuanian" },
    { label: "Македонски", value: "macedonian" },
    { label: "Bahasa Melayu", value: "malay" },
    { label: "മലയാളം", value: "malayalam" },
    { label: "Maltese", value: "maltese" },
    { label: "मराठी", value: "marathi" },
    { label: "Norsk", value: "norwegian" },
    { label: "فارسی", value: "persian" },
    { label: "Polski", value: "polish" },
    { label: "Português", value: "portuguese" },
    { label: "ਪੰਜਾਬੀ", value: "punjabi" },
    { label: "Română", value: "romanian" },
    { label: "Русский", value: "russian" },
    { label: "Српски", value: "serbian" },
    { label: "Slovenčina", value: "slovak" },
    { label: "Slovenščina", value: "slovenian" },
    { label: "Español", value: "spanish" },
    { label: "Kiswahili", value: "swahili" },
    { label: "Svenska", value: "swedish" },
    { label: "தமிழ்", value: "tamil" },
    { label: "తెలుగు", value: "telugu" },
    { label: "ไทย", value: "thai" },
    { label: "Türkçe", value: "turkish" },
    { label: "Українська", value: "ukrainian" },
    { label: "اردو", value: "urdu" },
    { label: "Tiếng Việt", value: "vietnamese" },
    { label: "Cymraeg", value: "welsh" },
    { label: "IsiXhosa", value: "xhosa" },
    { label: "ייִדיש", value: "yiddish" },
    { label: "Zulu", value: "zulu" }
]
